#A simple example of an ADC running on RPI2 and intel edison
FROM shaunmulligan/%%RESIN_MACHINE_NAME%%-node

ENV INITSYSTEM on
RUN node -v
COPY package.json /package.json
RUN npm install

COPY src/ /usr/src/app
CMD ["bash", "/usr/src/app/start.sh"]
